### ISSUE TITLE
Support for Neo4j 4.0

### ISSUE THREAD

**Issue by puneetbehl** [grails/gorm-neo4j#114]
References:

https://neo4j.com/docs/migration-guide/current/upgrade-driver/

**Comment by SwenVogel** [comment]
Hi, we are currently testing gorm-neo4j (7.0.1) with NEO4j (4.0.4). I don't know whether there any compatibility issues but we get an basic application (Spring Boot) woking after changing two configuration options.

**application.yml (in Spring Boot project)**

```
grails:
  neo4j:
    ...
    options:
        encryptionLevel: NONE
```

**conf/neo4j.conf (in NEO4j installation directory)**
```
cypher.default_language_version=3.5
```
